VALIS-33-fix-uncaught-JS-error
ENCODE-DCC/valis-hpgv pull request #19
Opened 2021-01-20 04:07 UTC by zoldello

2021-03-09 17:45 UTC, emro requested changes

2021-03-09 17:45 UTC, emro commented on src/ui/Panel.tsx
> +
This code seems reasonable and I think mostly works as I'd expect.

(a) If I enter "chr1:11102837-", I get "Second coordinate is invalid."
(b) If I enter "chr1:-11267747", I get "First coordinate is invalid."
(c) If I enter "chr1", I get "Cannot read property split of undefined."
(d) If I enter "chr1:", I get "First coordinate is undefined."

I'm not sure what entry results in the "Coordinates are invalid" error, and I think the errors for (c) should be fixed.

2021-03-12 17:13 UTC, zoldello commented
@forresttanaka The errors are user-facing. I can look into not throwing exceptions if you like in a different ticket.

2021-03-12 17:24 UTC, forresttanaka approved these changes
Didn’t realize they were user facing. But OK, that looks good.

2021-03-16 22:02 UTC, merged